use -e flag to fail entrypoint script

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -27,6 +27,10 @@ jobs:
           - uses: ./
             id: cac
             with:
-              args: --invalid cmd
-          - if: ${{ failure() }}
-            run: echo "Command failed as expected"
+              args: pull --invalid
+            continue-on-error: true
+          - if: steps.cac.outcome == 'success'
+            name: fail on cac success
+            run: exit 1
+          - if: steps.cac.outcome == 'failure'
+            run: echo "cac failed as expected"
